### ISSUE TITLE
SqlReadModel handling for aggregate collection data

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#165] opened 2015-10-31 05:38 UTC
@rasmus How do you handle creating read models for the following scenario using the `MsSqlReadStore` (or any `SQL` based read store):

- the aggregate is a job order (e.g. repair something)
- the job order aggregate has line items in a collection
- line items may be *owned* by other line items 

The job aggregate read model is not an issue as it maps to the `IMsSqlReadModel` and handles events via `IAmReadModelFor<,,>` with SQL generated targeting the `AggregateId` field in the table by `EventFlow.ReadStores.MsSql.ReadModelSqlGenerator`. 

A `ReadModelSqlGenerator` cannot be registered on a specific read model, only a `IReadModelLocator` can and in this case the read model requires specific SQL to select the line item.

How are the line items handled?

**Comment by rasmus** [comment] 2015-10-31 06:12
@JC008 Just to make sure that I understand the scenario. The job order is the entity implemented as the aggregate root, and the line items are basically entities in a collection on the job order.

If that's the case, then you could implement the read model like you would normally would, then implement an `IReadModelLocator` that merely returns the ID of the specific line item. So if you have a set of entity instances like this:

* job order with ID `1`
* line item with ID `a` belongs to job order `1`
* line item with ID `b` belongs to job order `1`

then the `IReadModelLocator` would return `a` and `b` for the domain events that are specific for those line items.

If that fails, then implement the read model logic manually using the `ISubscribeSynchronousTo`<,,>` interface.

If that doesn't solve your problem, or you have a better idea, let me know.

**Comment by JC008** [comment] 2015-10-31 06:41
@rasmus Here is another scenario matching the shipping example.

Cargo (or PAX) is never shipped without a manifest, the details of what the cargo contains as well as its international classifications as well as width, height, weight, value etc + [export duty codes](https://en.wikipedia.org/wiki/Harmonized_System)  e.g.

* 001 - 10 boxes of bananas - 2kg / 200x200x300, store below 10C in dark - IATA code XYZ1
* 002 - 3 crates of high explosives - 20kg / 2000x1000x1000 - IATA code ABS1

To update the read model for an item in the event that the manifest changes, the `IReadModelLocator` will return the correct id for the manifest entry (e.g. `001` to update the babanas entry) but the SQL will be `SELECT * FROM CargoManifest WHERE AggregateId = 001` and will not find the item. 

This is a case where an `IIdentity` (e.g. CargoItemId) is used but links to a collection in an aggregate and the readstore only targets aggregates.

**Comment by rasmus** [comment] 2015-11-03 22:03
@JC008 I have created a crude demo on how to use the read model locators. Have a look at #166 which shows how to create a read model for each item on an aggregate root and return the entire list in a query.

**Comment by rasmus** [comment] 2015-12-01 21:05
@JC008 Did the latest release of EventFlow solve your problem?

**Comment by JC008** [comment] 2015-12-03 12:35
@rasmus I started the conversion to the new read model approach but have a problem using the sql field name `Id` as a key field as it is being omitted from the insert sql generation. The original reason for protecting the field name was due to the auto increment used in the MsSqlReadModel which is now not needed.

**Comment by JC008** [comment] 2015-12-04 05:45
@rasmus The new light weight read model approach works like a charm, except for the `Id` field issue. I did a patch to remove the `Id` field exclusion on my side for 0.22 but deeper investigation is needed for a proper solution e.g. maybe detect if there is a `IReadModelLocator` for a read model before excluding it and specify that the the presence of an `IReadModelLocator` means the developer is taking full control of the read model table structure.

One thing the docs do not stress is when using a `IReadModelLocator` for a read model, it must be used for all events of an aggregate.

**Comment by rasmus** [comment] 2015-12-04 08:28
@JC008 I'll create a attribute that you can place on the columns to mark those you wan't to leave out and remove the `Id`. Its old and when I look in the code it seems more like a hack than a actual need.

@JC008 Could you describe the problem you have with the `IReadModelLocator` as the current integration tests use different read models for a subset of events from an aggregate. One read model uses the locator and the other doesn't.

**Comment by JC008** [comment] 2015-12-04 09:06
@rasmus If an `IReadModelLocator` is registered for a given read model, the locator must handle all events mapped to the read model via `IAmReadModelFor`. The docs should state it explicitly event though the example shows a result must always be returned (I missed that part from the code example).

**Comment by rasmus** [comment] 2015-12-05 08:46
@JC008 The locator should only be invoked for events that match the read model its used for. I created a set of tests in #180 that should illustrate this

**Comment by JC008** [comment] 2015-12-05 08:53
@rasmus Understood and used in that way, all works now as well - see my example code in #179

**Comment by rasmus** [comment] 2015-12-05 09:57
@JC008 Could you verify that the problem isn't present in 0.23.1469 that currently built.

You can download it here
https://ci.appveyor.com/project/rasmusnu/eventflow/build/0.23.1469/artifacts

Or use the NuGet feed
https://ci.appveyor.com/nuget/eventflow

**Comment by JC008** [comment] 2015-12-05 10:56
@rasmus All good - thanks,

**Comment by rasmus** [comment] 2015-12-05 13:18
@JC008 I'll close this as I release v0.23.1470

**Closed** 2015-12-05 13:18 UTC
